### ISSUE TITLE
Limite de zoom

### ISSUE THREAD

**Issue by tleb** [tleb/zds-user-map#2]
cf https://zestedesavoir.com/forums/sujet/9260/une-carte-des-membres-de-zeste-de-savoir/?page=8#p166083

Je n'arrive plus à me souvenir du pourquoi de la limite. Sauf si la raison était bonne, ça ne me dérange pas de la baisser ou de l'augmenter.

**Comment by WinXaito** [comment]
![image](https://user-images.githubusercontent.com/8223773/32667296-9a4e922c-c63a-11e7-9aef-4326fd9f4ebb.png)

https://zestedesavoir.com/forums/sujet/9260/une-carte-des-membres-de-zeste-de-savoir/?page=2#p161354

Donc à priori pour moi c'était une *fausse raison*.

**Comment by tleb** [comment]
Yep, ça ne te déranges pas de faire la modif stp ? Il suffit de supprimer [cette ligne](https://github.com/tleb/zds-user-map/blob/master/docs/main.js#L4). (Je n'ai plus d'env de dev sur mon PC, réinstall toute récente. :|)

**Comment by WinXaito** [comment]
Yep Yep, j'ai fait une PR #3, je te laisse regarder et merge si c'est ok pour toi.
